name: blog
description: "A new Flutter project."
publish_to: "none"
version: 1.2.2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  flutter_modular: ^6.3.4
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  flutter_secure_storage: ^9.2.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  cloud_firestore: ^5.5.1
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.2
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/splash.png
flutter_native_splash:
  color: "#2196F3"
  android: true
  ios: true
  android_12:
    image: assets/splash.png 
    icon_background_color: "#2196F3" 
    color: "#2196F3"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#2196F3"
  adaptive_icon_foreground: "assets/icon.png"
