name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/configure-pipeline
  pull_request:
    branches:
      - main
      - feature/configure-pipeline

jobs:
  build_google_services:
    name: Test google-services.json
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Configurar o JDK 17
      - name: Set up JDK 17
        run: |
          sudo apt update
          sudo apt install openjdk-17-jdk -y

      # 3. Configurar o Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"

      # 4. Criar google-services.json a partir do segredo Base64
      - name: Create google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > android/app/google-services.json

      # 5. Imprimir o conteúdo do google-services.json
      - name: Print google-services.json
        run: |
          echo "=== google-services.json Content ==="
          cat android/app/google-services.json

      # 6. Listar diretório para verificar o arquivo
      - name: Verify File Creation
        run: |
          ls -l android/app/
