name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/configure-pipeline
  pull_request:
    branches:
      - main
      - feature/configure-pipeline

jobs:
  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Configurar o JDK 17
      - name: Set up JDK 17
        run: |
          sudo apt update
          sudo apt install openjdk-17-jdk -y

      # 3. Configurar o Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"

      # 4. Instalar dependências do Flutter
      - name: Install Flutter Dependencies
        run: flutter pub get

      # 5. Criar google-services.json a partir do segredo Base64
      - name: Create google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > android/app/google-services.json

      # 6. Verificar se o arquivo google-services.json foi criado
      - name: Verify File Creation
        run: |
          ls -l android/app/

      # 7. Build do APK em modo release
      - name: Build Android APK
        run: flutter build apk --release

      # 8. Upload do APK como artefato
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
